name: kalda-prod
region: ams
envs:
- key: ROLLBAR_ENV
  scope: RUN_TIME
  value: prod-2
databases:
- engine: PG
  name: kalda-prod
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
services:
- name: kalda-prod
  github:
    branch: containers
    deploy_on_push: true
    repo: kalda-co/kalda
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  dockerfile_path: Dockerfile
  routes:
  - path: /
  envs:
  - key: SECRET_KEY_BASE
    scope: RUN_TIME
    type: SECRET
    value: EV[1:01VvtUFNgy0/WuRNu4w+3gk2VSAQIKgo:5xb44HaxY5DwzdtHMk5txZ4DJYAUmJTftkmMtY8qv5XGKdcmwZM5L3IxZoxul1A92tdWrxVdk4ByJ9lvR9JVV5BsxTV8BxHYG2siGHCrHPQ=]
  - key: SENDFOX_TOKEN
    scope: RUN_TIME
    type: SECRET
    value: EV[1:fbPCN1bmjjfVWmVg5Vo87p3zi4n/jKBd:RdiI7lYJLOULXx5SFL2MArS9FmXOsPeEcllV78WNER1XwwZKmfkWBOQXTGslWzp82dj/bBVtDjBgsj4QLG2XUJhgP74Am5zqdLSeJ19KMqyxrujNjYyLDUOMmxuqCINS4grae0oVJFJhiD+mduKMxFDy94OcXFeYY64tpYXjNy/wMaeSIU7o9eoc37ciIW3Dmn7hO5CbxYkoFVtVj7LVIZcrSy0seVEoDJHCHUaxstmXGOXr2qwFPv2i6gAGfxOK8698jgYVP9E+UyrW3ofq0fWUHrfwqhM7NVsxMXT8zMLXm9MsQbEG6B9IuL8FN+l9D2A8R0uOQGhQbLr0+acf9pHqo4m3BiVX5/0E96kyzgKF47GKQHa7Uhp0K1dZXwKXAuGLWxxlu3FpN2jX2n+9LtEEI4brfs+tjW60dtzl++KpI4wi8r4BlrlvH937bW36wHUvhMggrSfQ8BBoLT4yqSSW8MVkeuWhUPNzOu/4rEjDDRfWTdHEw/7JZxja7wMv93qbHXlgxXVkE13aAE2GmLbGwcjKKckfYXixjBKwQyhZxfqyNMHsM7j/EwBi7cfkoFdgb3xwY0tbd6sLASUm7pCb+A6yQBK6M6fkvfjmN26tzSWbbmXDqTld+zyWBNXeYYw0rxR9IjS2CEDYNImLXooLcE+gX4b/OeOlkteTE38U8cSfBdnXXNgDVBsaw11EgBiIZ0fZDUMgW2iLxkzHj0az5n50pQKCFGZVeu4StKFfhaPW9n8KkOlog/g2JixEFuAMAHHrDWspr8UO0hAH+lkSRGl6Dr5o9OXJEpLbkuERNgVllkzSidcVIoA7Nvc7+KZ2C04pNKhBLBEOeNSebe1B52GOvjoiwgbzKJc0hOPj2AqX0/j2GPplH+ATV4PdeAw8m7xctfxG/yBdhxD8LOih6ULAHkJ1Nj8RdJ6/szf9OrMlX4KPwTgw+jCw37VS1VhyLqh+TduApMJ69ExNAccJrinraCFyrW+8svCzTQBX7ZnNaGRtxRyg39oplUglvvVTRKipUXEIu3G4GJTJyfcq0WznbQUAoU+023y2YHBDzRlzWop2wbqjrVuf2T6cu7N2KU5klu10xUKtMfRnvtkUC0O0CRKDCKyohTQenhPSEgp63szEfqTZjv5FpE8lh9x634MnZkdozr93OfvWbIvxzPuzFGaXDcNy2JBJ9v+evRNj9Bk7PNtcn4oyM5EJkGVxSekANBTbYm8K/Pd7FmKsGa8oJl0DrCvr0EX/IrOc0PYL5p1/SMJVUvU7cwoCrlE5bnCdTb3VZBVvj0Ao6QKnV9C4VM64OVmVdNmI7zh78mj0n2e6CUJgx8dNtxAtXRzWngC8YM/sLOT20ctcOyU3MwRvQ74EAJkBIU1QnTyudyKlTACZMDeh9uTCzGczd6ciurmgYNuZc2mikIYkYVKqk7DIGDljNGhib9WAo6cm+yWb]
  - key: SENDGRID_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:Grtq5gem1x6gu0H/o2sG1PVn76lHOkhe:zzSJmKIGBinIYcOaINgZ7DlTHW3EJIr7uoJ23fmvbelEkJ5fqWxcMn0XY2RfB8M2+zSSEADnf+nc9rApuw/ALPzZ6AZNuwBRFhnrds6eePazkPYKMA==]
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${kalda-prod.DATABASE_URL}
